import { Box, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { animated, useSpring } from "react-spring";

export default function Layout({ children }: { children: React.ReactNode }) {
  const logoRatio = 2077 / 921;
  const logoHeight = 125;
  const logoWidth = logoHeight * logoRatio;
  const [scroll, setScroll] = useState(0);

  const animation = useSpring({
    from: { scroll: 0 },
    to: { scroll },
  });

  const AnimatedStack = animated(Stack);

  const handleClick = () => {
    console.log("clicked");
    setScroll(scroll + 500);
  };

  return (
    <>
      <AnimatedStack
        direction="column"
        height="400vh"
        alignItems="center"
        scrollTop={scroll}
        overflow="auto"
      >
        <Stack
          direction="row"
          spacing={10}
          alignItems="center"
          justifyContent="center"
          position="fixed"
          top={0}
          bgcolor="white"
        >
          <Typography sx={{ cursor: "pointer" }} onClick={handleClick}>
            Home
          </Typography>
          <Typography sx={{ cursor: "pointer" }}>About</Typography>
          <Typography sx={{ cursor: "pointer" }}>Services</Typography>
          <Typography sx={{ cursor: "pointer" }}>Contact</Typography>
          <Box marginLeft="auto">
            <Image
              src="/logo-blue-01.svg"
              alt="Claro Creative Logo"
              width={logoWidth}
              height={logoHeight}
            />
          </Box>
        </Stack>
        {children}
      </AnimatedStack>
      <Head>
        <title>Claro Creative Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
