import { Box, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Layout({ children }: { children: React.ReactNode }) {
  const logoRatio = 2077 / 921;
  const logoHeight = 125;
  const logoWidth = logoHeight * logoRatio;
  return (
    <>
      <Stack direction="column" spacing={4}>
        <Stack
          direction="row"
          spacing={10}
          alignItems="center"
          justifyContent="flex-end"
        >
          <Link href="/">
            <Typography sx={{ cursor: "pointer" }}>Home</Typography>
          </Link>
          <Link href="/about">
            <Typography sx={{ cursor: "pointer" }}>About</Typography>
          </Link>
          <Link href="/services">
            <Typography sx={{ cursor: "pointer" }}>Services</Typography>
          </Link>
          <Link href="/contact">
            <Typography sx={{ cursor: "pointer" }}>Contact</Typography>
          </Link>
          <Box>
            <Image
              src="/logo-blue-01.svg"
              alt="Claro Creative Logo"
              width={logoWidth}
              height={logoHeight}
            />
          </Box>
        </Stack>
        {children}
      </Stack>
      <Head>
        <title>Claro Creative Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
