import { Box, Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const logoRatio = 2077 / 921;
  const logoHeight = 125;
  const logoWidth = logoHeight * logoRatio;

  return (
    <>
      <Stack direction="row" spacing={10} alignItems="center">
        <Box>
          <Image
            src="/logo-blue-01.svg"
            alt="Claro Creative Logo"
            width={logoWidth}
            height={logoHeight}
          />
        </Box>
        <Typography>Home</Typography>
        <Typography>About</Typography>
      </Stack>
      <Head>
        <title>Claro Creative Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
